### ISSUE TITLE
AdFitBannerSize.SMALL_BANNER 가 적용되지 않습니다

### ISSUE THREAD

**Issue by ksncho** [HuanSuh/flutter-kakao-adfit#3]
안녕하세요. 패키지 정말 감사하게 잘 사용하고 있습니다. ^^

그런데, AdFitBannerSize를 SMALL_BANNER 로 설정해도 위젯의 크기는 변경 되는데 광고의 크기는 변경이 안되는 것 같습니다.
제가 뭔가 잘 못 사용하고 있는 것일까요? ㅜㅜ

앱의 하단부에 광고가 노출되고 있는데, SMALL_BANNER로 설정하면 아래 화면과 같이 위젯의 높이는 줄어드는데 광고 내용물은 그대로 입니다.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1950642/168024187-36fc2abc-88fe-40ce-8d4c-e822da256394.png">

BANNER로 설정하면 아래와 같이 정상적으로 보여집니다.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1950642/168024435-6820267e-0fa8-4fd7-b4d3-c3cb69e8e4b9.png">

**Comment by HuanSuh** [comment]
안녕하세요, 해당 이슈 체크해보겠습니다.
다만, AdFit에서 제공되는 광고 자체 이슈일 수 있을 것 같아 해당 부분도 확인해보시기 바랍니다.

**Comment by ksncho** [comment]
제가 애드핏 쪽에서 잘못 설정한 것이었네요;;
설정을 변경한 후에 정상 작동 하는 것을 확인 하였습니다.
번거롭게 해드려 죄송합니다 ㅜㅜ

![image](https://user-images.githubusercontent.com/1950642/168991948-54ba41c3-378e-4847-9327-bb146f580cec.png)
