### ISSUE TITLE
Flutter Andriod 빌드 오류

### ISSUE THREAD

**Issue by DotJM** [HuanSuh/flutter-kakao-adfit#4]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven2(http://devrepo.kakao.com:8088/nexus/content/groups/public/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. 

라는 에러가 발생되며 빌드가 진행되지 않습니다...ㅠㅠ

검색해보니깐 안드로이드 adfit sdk 에서 
https://devtalk.kakao.com/t/gradle-7-0/104816 이런 내용이 있던데 이 내용 관련으로 대응이 안된걸까요?? 아니면 제 문제 인걸까요??

**Comment by hajini** [comment]
@dotjm 저도 동일한 증상으로 에러가 나네요. 업데이트가 안되나 보네요

**Comment by HuanSuh** [comment]
Closed https://github.com/HuanSuh/flutter-kakao-adfit/pull/5
