### ISSUE TITLE
flutter에서 Workmanager API와 같이 사용하면 오류 발생합니다.

### ISSUE THREAD

**Issue by nicelee777** [HuanSuh/flutter-kakao-adfit#7]
flutter로 홈위젯을 업데이트하기 위해 workmanager 0.5.2 를 사용하고 있는데 백드라우든 프로세스가 실행되면 오류발생합니다.
이것과 관련이 있는지 모르겠지만 메모리에서 제거하는 기능이 없어(dispose()) 테스트 중에 다른 오류들이 있었습니다. 치명적인 오류는 아니어서 프로세스가 죽지는 안았는데, 이 오류는 앱이 죽습니다.
빠른 조치 부탁드립니다.
--------------------------------
E/AndroidRuntime( 9710): kotlin.UninitializedPropertyAccessException: lateinit property adView has not been initialized
E/AndroidRuntime( 9710): 	at flutter.kakao.flutter_adfit.AdViewFactory.onDestroy(AdViewFactory.kt:23)
E/AndroidRuntime( 9710): 	at flutter.kakao.flutter_adfit.FlutterAdfitPlugin.onDetachedFromEngine(FlutterAdfitPlugin.kt:24)
E/AndroidRuntime( 9710): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
E/AndroidRuntime( 9710): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:282)
E/AndroidRuntime( 9710): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:290)
E/AndroidRuntime( 9710): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
E/AndroidRuntime( 9710): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:460)
E/AndroidRuntime( 9710): 	at dev.fluttercommunity.workmanager.BackgroundWorker.stopEngine$lambda$3(BackgroundWorker.kt:143)
E/AndroidRuntime( 9710): 	at dev.fluttercommunity.workmanager.BackgroundWorker.$r8$lambda$YX_kSwcT9UnNdOdlpnrG92Wu8AY(Unknown Source:0)
E/AndroidRuntime( 9710): 	at dev.fluttercommunity.workmanager.BackgroundWorker$$ExternalSyntheticLambda2.run(Unknown Source:2)
E/AndroidRuntime( 9710): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 9710): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9710): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 9710): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 9710): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 9710): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9710): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 9710): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by HuanSuh** [comment]
@nicelee777  
stacktrace로 추정되는 오류 수정하였습니다.
[flutter_adfit: 1.2.1](https://pub.dev/packages/flutter_adfit/versions/1.2.1) 버전 확인 후 이상있으면 말씀해주세요
